
const Nouns = [
    "alligator chaser",
    "alpaca",
    "antelope",
    "armadillo",
    "donkey",
    "badger",
    "bat",
    "bear herder",
    "beaver",
    "bee",
    "buffalo",
    "butterfly",
    "camel",
    "caribou",
    "cat",
    "cheetah",
    "chimpanzee",
    "chinchilla",
    "coyote",
    "daisy",
    "deer",
    "dolphin",
    "duck",
    "elk",
    "ferret",
    "fox",
    "giraffe",
    "goldfish",
    "gorilla keeper",
    "grasshopper",
    "grey wolf",
    "guinea pig",
    "hedgehog",
    "horse",
    "jellyfish",
    "kangaroo",
    "koala",
    "land-mermaid",
    "leopard",
    "lion",
    "death-defying llama",
    "macaw",
    "mallard",
    "manatee",
    "mannequin come to life",
    "mink",
    "moth",
    "muskox",
    "newborn baby",
    "nurse",
    "orchid",
    "circus otter",
    "crime fighting oyster",
    "panda",
    "pig",
    "platypus",
    "poppy",
    "porcupine",
    "porpoise",
    "prairie dog",
    "super",
    "rabbit",
    "raccoon",
    "reindeer",
    "dew flecked rose",
    "sacred lotus",
    "salmon",
    "sardine",
    "sea",
    "seal",
    "shakespearean actor",
    "shark",
    "space lion",
    "space unicorn",
    "spinster",
    "squirrel",
    "super pig",
    "sunflower",
    "sunfish",
    "sunken treasure",
    "sun goddess",
    "swan",
    "tiger",
    "tortoise",
    "tree shark",
    "tropical fish",
    "trout detective",
    "turtle wrangler",
    "underwear model",
    "wallaby",
    "wild pig",
    "wolf",
    "wombat",
    "zebra"
];

export default Nouns;